### ISSUE TITLE
Please add subpage reorder

### ISSUE THREAD

**Issue by Seppentoni** [jannisg/statamic-pagereorder#3]
Hi.

It would be awesome to be able to reorder subpages.

My client wants to reorder pages, but the only possibility is to alter the slug.
Which is not very usability friendly.

Wouldn't this be easy possible trough grabbing the foldername number of the subpage and alter this number trough the reorder plugin?

Thank you

**Comment by jannisg** [comment]
@Seppentoni Perhaps I'm missing something but according to the Statamic Docs on ["Managing Members"](http://statamic.com/learn/control-panel/managing-members) there are no roles/user groups other than `admin` or `no admin`.

> Roles exist to limit what particular members have access to. At the moment, the only role you can choose from is “admin”. Members with the “admin” role will be able to access the control panel, and those without it will not.

Thanks for your feedback, will have a look at this stuff sometime this weekend I think.

**Comment by jannisg** [comment]
@Seppentoni @Motifsky @pieterclaerhout @hollingberry I've released `0.3.0` on `master` which should (in my limited testing anyway) add subpage reordering on the dashboard.

![statamic-1 9-subpagereordering](https://cloud.githubusercontent.com/assets/109211/5691040/45a3ae3a-9918-11e4-9657-b1d5e0128057.png)

Would any of you mind trying this out and reporting back any bugs?

**Comment by Motifsky** [comment]
will get a quick dev install set-up and report back! 

BROOK
303-519-4553

**Comment by pieterclaerhout** [comment]
Seems to work like a charm for me!

**Comment by jannisg** [comment]
Nice one. Closing this issue.

Thanks for running over this @pieterclaerhout!
